// BTCVault contract ABI — IBTCVault interface
export const VAULT_ABI = [
  {
    type: "function",
    name: "deposit",
    inputs: [{ name: "amount", type: "core::integer::u256" }],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [{ name: "ybtc_amount", type: "core::integer::u256" }],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "apply_leverage",
    inputs: [{ name: "target_leverage", type: "core::integer::u128" }],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "deleverage",
    inputs: [],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_user_position",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "(core::integer::u256, core::integer::u256, core::integer::u128)" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_share_price",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_total_assets",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_total_debt",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_debt",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_apy",
    inputs: [],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_btc_usd_price",
    inputs: [],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_health",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_liquidation_price",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_liquidatable",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_dashboard",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "vault::interfaces::UserDashboard" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_claimable_yield",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "claim_yield",
    inputs: [],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_recommended_leverage",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "set_user_mode",
    inputs: [
      { name: "mode", type: "vault::interfaces::UserMode" },
      { name: "yield_strategy", type: "core::starknet::contract_address::ContractAddress" },
      { name: "custom_leverage_cap", type: "core::integer::u128" },
      { name: "custom_yield_bps", type: "core::integer::u16" },
      { name: "accept_warning", type: "core::bool" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "struct",
    name: "vault::interfaces::UserDashboard",
    members: [
      { name: "ybtc_balance",          type: "core::integer::u256" },
      { name: "btc_value_sat",         type: "core::integer::u256" },
      { name: "btc_value_usd",         type: "core::integer::u256" },
      { name: "current_leverage",      type: "core::integer::u128" },
      { name: "user_debt_usd",         type: "core::integer::u256" },
      { name: "health_factor",         type: "core::integer::u128" },
      { name: "liquidation_price_usd", type: "core::integer::u128" },
      { name: "claimable_yield_sat",   type: "core::integer::u256" },
      { name: "yield_strategy",        type: "core::starknet::contract_address::ContractAddress" },
      { name: "mode",                  type: "core::integer::u8" },
      { name: "custom_leverage_cap",   type: "core::integer::u128" },
      { name: "custom_yield_bps",      type: "core::integer::u16" },
      { name: "warning_accepted",      type: "core::bool" },
      { name: "deposit_timestamp",     type: "core::integer::u64" },
      { name: "share_price",           type: "core::integer::u256" },
      { name: "vault_apy",             type: "core::integer::u128" },
      { name: "price_is_fresh",        type: "core::bool" },
      { name: "is_safe_mode",          type: "core::bool" },
      { name: "recommended_leverage",  type: "core::integer::u128" },
      { name: "recommended_strategy",  type: "core::starknet::contract_address::ContractAddress" },
      { name: "can_deposit",           type: "core::bool" },
      { name: "can_leverage",          type: "core::bool" },
    ],
  },
] as const;
