// BTCVault contract ABI — IBTCVault interface
export const VAULT_ABI = [
  {
    type: "function",
    name: "deposit",
    inputs: [{ name: "amount", type: "core::integer::u256" }],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [{ name: "ybtc_amount", type: "core::integer::u256" }],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "apply_leverage",
    inputs: [{ name: "target_leverage", type: "core::integer::u128" }],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "deleverage",
    inputs: [],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_user_position",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "(core::integer::u256, core::integer::u256, core::integer::u128)" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_share_price",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_total_assets",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_total_debt",
    inputs: [],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_apy",
    inputs: [],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_btc_usd_price",
    inputs: [],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_health",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_liquidation_price",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_liquidatable",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_dashboard",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "vault::interfaces::UserDashboard" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_claimable_yield",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "claim_yield",
    inputs: [],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_recommended_leverage",
    inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
    outputs: [{ type: "core::integer::u128" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "set_user_mode",
    inputs: [
      { name: "mode", type: "vault::interfaces::UserMode" },
      { name: "yield_strategy", type: "core::starknet::contract_address::ContractAddress" },
      { name: "custom_leverage_cap", type: "core::integer::u128" },
      { name: "custom_yield_bps", type: "core::integer::u16" },
      { name: "accept_warning", type: "core::bool" },
    ],
    outputs: [],
    state_mutability: "external",
  },
] as const;
